# why are there different conventions for the tool names :(

TRAINING_DATA = [
    # searchWeb
    ("search the web for current gold prices", "searchWeb"),
    ("google latest SpaceX mission", "searchWeb"),
    ("look up who won the match", "searchWeb"),
    ("search for the nearest pizza place", "searchWeb"),
    ("search python tutorials", "searchWeb"),
    ("google the population of india", "searchWeb"),
    ("look up best laptops 2026", "searchWeb"),
    ("find me cricket scores", "searchWeb"),
    ("search karo iphone price", "searchWeb"),
    ("search for machine learning jobs", "searchWeb"),
    ("look up capital of france", "searchWeb"),
    ("find nearby restaurants", "searchWeb"),
    ("google search jiit placements", "searchWeb"),
    ("search for good running shoes", "searchWeb"),
    ("look up jiit hostel fees", "searchWeb"),
    ("find me some biryani places nearby", "searchWeb"),
    ("search online for stock market trends", "searchWeb"),
    ("search internet for best hotels in Goa", "searchWeb"),
    ("browse the web for cheap flights", "searchWeb"),
    ("look up recipe for paneer butter masala", "searchWeb"),
    ("google today's gold rate", "searchWeb"),
    ("search web for electric cars comparison", "searchWeb"),
    ("find information about upcoming eclipses online", "searchWeb"),

    # searchYoutube
    ("play lofi music on YouTube", "searchYoutube"),
    ("find python tutorial videos", "searchYoutube"),
    ("search youtube for interstellar soundtrack", "searchYoutube"),
    ("open youtube and play songs", "searchYoutube"),
    ("watch gameplay videos on youtube", "searchYoutube"),
    ("search youtube for workout routine", "searchYoutube"),
    ("find cooking recipes on youtube", "searchYoutube"),
    ("play coldplay songs on youtube", "searchYoutube"),
    ("search youtube for math lectures", "searchYoutube"),
    ("find trailer on youtube", "searchYoutube"),
    ("watch highlights on youtube", "searchYoutube"),
    ("play funny cat videos on yt", "searchYoutube"),
    ("search yt for podcast episode", "searchYoutube"),
    ("youtube search data structures playlist", "searchYoutube"),
    ("find stand up comedy on youtube", "searchYoutube"),
    ("search video tutorial on youtube", "searchYoutube"),
    ("open youtube music", "searchYoutube"),
    ("look up video on youtube", "searchYoutube"),
    ("search on youtube for funny clips", "searchYoutube"),
    ("play lo-fi beats on youtube", "searchYoutube"),

    # searchWikipedia
    ("who was Alan Turing", "searchWikipedia"),
    ("tell me about quantum computing from wikipedia", "searchWikipedia"),
    ("history of the Roman Empire", "searchWikipedia"),
    ("search wikipedia for Albert Einstein", "searchWikipedia"),
    ("wiki summary of photosynthesis", "searchWikipedia"),
    ("look up industrial revolution on wikipedia", "searchWikipedia"),
    ("who is the prime minister of japan wikipedia", "searchWikipedia"),
    ("wikipedia article on black holes", "searchWikipedia"),
    ("tell me the history of india from wiki", "searchWikipedia"),
    ("search wiki for machine learning", "searchWikipedia"),
    ("biography of Isaac Newton on wikipedia", "searchWikipedia"),
    ("what does wikipedia say about Mars", "searchWikipedia"),
    ("look up theory of relativity on wikipedia", "searchWikipedia"),
    ("wiki information on world war 2", "searchWikipedia"),
    ("search wikipedia for French Revolution", "searchWikipedia"),
    ("what is DNA according to wikipedia", "searchWikipedia"),
    ("wiki page of python programming language", "searchWikipedia"),
    ("read wikipedia article on Renaissance", "searchWikipedia"),
    ("search wiki for artificial intelligence", "searchWikipedia"),
    ("who was alexander the great according to wikipedia", "searchWikipedia"),

    # create_folder
    ("create a folder named test", "create_folder"),
    ("make a directory called project_files", "create_folder"),
    ("create folder assets", "create_folder"),
    ("make a new directory", "create_folder"),
    ("create a folder for photos", "create_folder"),
    ("create directory called src", "create_folder"),
    ("make a folder named documents", "create_folder"),
    ("create new directory backup", "create_folder"),
    ("make folder models", "create_folder"),
    ("i need a new folder called data", "create_folder"),
    ("create directory utils", "create_folder"),
    ("make a directory for assignments", "create_folder"),
    ("ek naya folder bana do", "create_folder"),
    ("create folder named temp", "create_folder"),
    ("make a directory test_dir", "create_folder"),
    ("create folder images", "create_folder"),
    ("make a new folder on my desktop", "create_folder"),
    ("create directory build", "create_folder"),

    # create_file
    ("create a file named notes.txt", "create_file"),
    ("make a file called todo.md", "create_file"),
    ("write a new file config.json", "create_file"),
    ("create a new file", "create_file"),
    ("new file please", "create_file"),
    ("make a text file", "create_file"),
    ("create script.py", "create_file"),
    ("create file named todo", "create_file"),
    ("make a file sample.csv", "create_file"),
    ("ek naya file bana do", "create_file"),
    ("touch main.py", "create_file"),
    ("create an empty file data.txt", "create_file"),
    ("make a new file called app.py", "create_file"),
    ("write a file named style.css", "create_file"),
    ("create file report.pdf", "create_file"),
    ("start a new document file", "create_file"),
    ("create a file called index.html", "create_file"),
    ("make file notes.md", "create_file"),

    # read_file
    ("read file notes.txt", "read_file"),
    ("what is inside readme.md", "read_file"),
    ("open and show me data.csv", "read_file"),
    ("display contents of script.py", "read_file"),
    ("read the config.json file", "read_file"),
    ("show me what is in todo.md", "read_file"),
    ("print the content of log.txt", "read_file"),
    ("view file index.html", "read_file"),
    ("cat main.py", "read_file"),
    ("open file results.txt and display it", "read_file"),
    ("show file contents for data.json", "read_file"),
    ("read contents of requirements.txt", "read_file"),
    ("check the content of file info.txt", "read_file"),
    ("display data from records.csv", "read_file"),
    ("open and read my notes.txt", "read_file"),
    ("view output.log", "read_file"),
    ("read what is written in summary.txt", "read_file"),
    ("show me the text in document.txt", "read_file"),

    # get_weather
    ("what's the weather in Delhi", "get_weather"),
    ("is it raining in Mumbai", "get_weather"),
    ("current temperature in New York", "get_weather"),
    ("what's the weather", "get_weather"),
    ("weather today", "get_weather"),
    ("is it raining outside", "get_weather"),
    ("tell me the temperature", "get_weather"),
    ("will it rain tomorrow", "get_weather"),
    ("weather forecast please", "get_weather"),
    ("aaj mausam kaisa hai", "get_weather"),
    ("how hot is it today", "get_weather"),
    ("check weather for delhi", "get_weather"),
    ("do i need an umbrella today", "get_weather"),
    ("kal mausam kaisa rahega", "get_weather"),
    ("weather update for london", "get_weather"),
    ("temperature in tokyo right now", "get_weather"),
    ("is it sunny in bangalore", "get_weather"),
    ("check humidity and precipitation today", "get_weather"),
    ("weather in seattle", "get_weather"),
    ("will it snow today", "get_weather"),

    # get_news
    ("give me today's top headlines", "get_news"),
    ("latest technology news", "get_news"),
    ("what's the news in sports", "get_news"),
    ("show me breaking news", "get_news"),
    ("latest world news today", "get_news"),
    ("news headlines for today", "get_news"),
    ("what is happening in politics news", "get_news"),
    ("give me financial news update", "get_news"),
    ("latest cricket news", "get_news"),
    ("show me entertainment news", "get_news"),
    ("top news stories right now", "get_news"),
    ("aaj ki taaja khabar", "get_news"),
    ("read today's daily news", "get_news"),
    ("give me the daily news digest", "get_news"),
    ("what are the global news headlines", "get_news"),
    ("business news updates today", "get_news"),
    ("what is in the morning news", "get_news"),
    ("fetch current news updates", "get_news"),
    
    # convert_currency
    ("convert 500 USD to INR", "convert_currency"),
    ("how much is 100 EUR in JPY", "convert_currency"),
    ("convert 50 GBP to CAD", "convert_currency"),
    ("convert 1000 rupees to dollars", "convert_currency"),
    ("how many euros is 50 USD", "convert_currency"),
    ("exchange rate from USD to INR", "convert_currency"),
    ("convert 250 AUD to EUR", "convert_currency"),
    ("what is 100 CAD in USD", "convert_currency"),
    ("convert 5000 yen to usd", "convert_currency"),
    ("currency conversion 200 euro in inr", "convert_currency"),
    ("convert 100 dollar to rupee", "convert_currency"),
    ("what is 50 pounds in dirhams", "convert_currency"),
    ("exchange 300 SGD to USD", "convert_currency"),
    ("convert 75 EUR to GBP", "convert_currency"),
    ("how much is 1000 INR in USD", "convert_currency"),
    ("currency exchange 500 USD to EUR", "convert_currency"),
    ("convert 200 AUD to INR", "convert_currency"),
    ("exchange rate between euro and dollar", "convert_currency"),

    # edit_file
    ("edit the file notes.txt", "edit_file"),
    ("append text to log.txt", "edit_file"),
    ("modify config.json", "edit_file"),
    ("add a new line to todo.md", "edit_file"),
    ("update readme.md with new instructions", "edit_file"),
    ("overwrite the content of test.py", "edit_file"),
    ("change the contents of data.csv", "edit_file"),
    ("edit my script main.py", "edit_file"),
    ("append this text to notes.txt", "edit_file"),
    ("update info.txt file", "edit_file"),
    ("write more lines to output.log", "edit_file"),
    ("modify the text in todo.txt", "edit_file"),
    ("edit index.html to add a header", "edit_file"),
    ("is file me ye add kardo", "edit_file"),
    ("append done to status.txt", "edit_file"),

    # save_memory
    ("remember that my name is Rushil", "save_memory"),
    ("save this fact about me", "save_memory"),
    ("keep in mind that I live in Delhi", "save_memory"),
    ("memorize that my favorite language is C++", "save_memory"),
    ("remember my birthday is on September 8th", "save_memory"),
    ("save to memory that I am not allergic to peanuts", "save_memory"),
    ("remember that my dog's name was Jojo", "save_memory"),
    ("keep this in memory: I work as a backend dev", "save_memory"),
    ("ye yaad rakhna ki mujhe coffee pasand hai", "save_memory"),
    ("remember that I prefer dark mode", "save_memory"),
    ("save memory city is Mumbai", "save_memory"),
    ("memorize my email address", "save_memory"),
    ("remember that I like rock music", "save_memory"),
    ("remember that my favourite artist is Lana Del Rey", "save_memory"),

    # recall_memory
    ("what do you remember about me", "recall_memory"),
    ("recall my saved facts", "recall_memory"),
    ("what is my name according to your memory", "recall_memory"),
    ("what is my favorite language", "recall_memory"),
    ("tell me everything you remember", "recall_memory"),
    ("show saved memories", "recall_memory"),
    ("where do I live", "recall_memory"),
    ("kuch yaad hai mere baare me", "recall_memory"),
    ("recall what my city is", "recall_memory"),
    ("what facts do you know about me", "recall_memory"),
    ("list all memories", "recall_memory"),
    ("check memory for my birthday", "recall_memory"),

    # forget_memory
    ("forget my name", "forget_memory"),
    ("delete the memory about my city", "forget_memory"),
    ("forget that I live in Delhi", "forget_memory"),
    ("remove my favorite food from memory", "forget_memory"),
    ("forget all about my dog", "forget_memory"),
    ("forget about her", "forget_memory"),  # ouch
    ("delete saved memory for email", "forget_memory"),
    ("ye memory bhool jao", "forget_memory"),
    ("erase my birthday from memory", "forget_memory"),
    ("forget the fact about my college", "forget_memory"),
    ("clear memory for hobby", "forget_memory"),

    # ingest_document
    ("teach document notes.pdf", "ingest_document"),
    ("ingest this document paper.pdf", "ingest_document"),
    ("load document presentation.pptx", "ingest_document"),
    ("train on file doc.txt", "ingest_document"),
    ("ingest research_paper.pdf into RAG", "ingest_document"),
    ("read and index lecture_notes.pdf", "ingest_document"),
    ("learn from document thesis.pdf", "ingest_document"),
    ("add report.pdf to knowledge base", "ingest_document"),
    ("ingest file data_summary.txt", "ingest_document"),
    ("load this pdf into memory", "ingest_document"),

    # ask_document
    ("ask document what is the main conclusion", "ask_document"),
    ("search document for methodology section", "ask_document"),
    ("what does the document say about revenue", "ask_document"),
    ("query the ingested document about chapter 3", "ask_document"),
    ("according to the pdf what is the author name", "ask_document"),
    ("find section 4 in the document", "ask_document"),
    ("what is mentioned in the uploaded ppt", "ask_document"),
    ("ask the paper what dataset was used", "ask_document"),
    ("search the active doc for summary", "ask_document"),
    ("doc me kya likha hai about testing", "ask_document"),

    # LLM
    ("hello", "LLM"),
    ("who are you", "LLM"),
    ("tell me a joke", "LLM"),
    ("explain binary search", "LLM"),
    ("write a poem", "LLM"),
    ("explain recursion", "LLM"),
    ("teach me binary trees", "LLM"),
    ("what is a linked list", "LLM"),
    ("how does gradient descent work", "LLM"),
    ("summarize this document for me", "LLM"),
    ("help me debug my code", "LLM"),
    ("explain how transformers work", "LLM"),
    ("what's the difference between tcp and udp", "LLM"),
    ("what is 2 plus 2", "LLM"),
    ("what is the meaning of life", "LLM"),
    ("write a short story about a robot", "LLM"),
    ("how do I cook pasta", "LLM"),
    ("tell me a motivational quote", "LLM"),
    ("hi how are you", "LLM"),
    ("explain quantum computing in simple words", "LLM"),
    ("what is the fullform of IEEE", "LLM"),
    ("what's up", "LLM"),
    ("whats up", "LLM"),
    ("what is up", "LLM"),
    ("hey what's up", "LLM"),
    ("yo what's up", "LLM"),
    ("good morning", "LLM"),
    ("good evening", "LLM"),
    ("how are you doing today", "LLM"),
    ("sup bro", "LLM"),
    ("kaisa hai yaar", "LLM"),
    ("write a python script to reverse a string", "LLM"),
    ("can you generate a story for me", "LLM"),
    ("write a blog post about artificial intelligence", "LLM"),
]
