# why are there different conventions for the tool names :(

TRAINING_DATA = [
    # searchWeb
    ("search the web for current gold prices", "searchWeb"),
    ("google latest SpaceX mission", "searchWeb"),
    ("look up who won the match", "searchWeb"),
    ("search for the nearest pizza place", "searchWeb"),
    ("search python tutorials", "searchWeb"),
    ("google the population of india", "searchWeb"),
    ("look up best laptops 2026", "searchWeb"),
    ("find me cricket scores", "searchWeb"),
    ("search karo iphone price", "searchWeb"),
    ("search for machine learning jobs", "searchWeb"),
    ("look up capital of france", "searchWeb"),
    ("find nearby restaurants", "searchWeb"),
    ("google search jiit placements", "searchWeb"),
    ("search for good running shoes", "searchWeb"),
    ("look up jiit hostel fees", "searchWeb"),
    ("find me some biryani places nearby", "searchWeb"),
    ("search online for stock market trends", "searchWeb"),
    ("search internet for best hotels in Goa", "searchWeb"),
    ("browse the web for cheap flights", "searchWeb"),
    ("look up recipe for paneer butter masala", "searchWeb"),
    ("google today's gold rate", "searchWeb"),
    ("search web for electric cars comparison", "searchWeb"),
    ("find information about upcoming eclipses online", "searchWeb"),

    # searchYoutube
    ("play lofi music on YouTube", "searchYoutube"),
    ("find python tutorial videos", "searchYoutube"),
    ("search youtube for interstellar soundtrack", "searchYoutube"),
    ("open youtube and play songs", "searchYoutube"),
    ("watch gameplay videos on youtube", "searchYoutube"),
    ("search youtube for workout routine", "searchYoutube"),
    ("find cooking recipes on youtube", "searchYoutube"),
    ("play coldplay songs on youtube", "searchYoutube"),
    ("search youtube for math lectures", "searchYoutube"),
    ("find trailer on youtube", "searchYoutube"),
    ("watch highlights on youtube", "searchYoutube"),
    ("play funny cat videos on yt", "searchYoutube"),
    ("search yt for podcast episode", "searchYoutube"),
    ("youtube search data structures playlist", "searchYoutube"),
    ("find stand up comedy on youtube", "searchYoutube"),
    ("search video tutorial on youtube", "searchYoutube"),
    ("open youtube music", "searchYoutube"),
    ("look up video on youtube", "searchYoutube"),
    ("search on youtube for funny clips", "searchYoutube"),
    ("play lo-fi beats on youtube", "searchYoutube"),

    # searchWikipedia
    ("who was Alan Turing", "searchWikipedia"),
    ("tell me about quantum computing from wikipedia", "searchWikipedia"),
    ("history of the Roman Empire", "searchWikipedia"),
    ("search wikipedia for Albert Einstein", "searchWikipedia"),
    ("wiki summary of photosynthesis", "searchWikipedia"),
    ("look up industrial revolution on wikipedia", "searchWikipedia"),
    ("who is the prime minister of japan wikipedia", "searchWikipedia"),
    ("wikipedia article on black holes", "searchWikipedia"),
    ("tell me the history of india from wiki", "searchWikipedia"),
    ("search wiki for machine learning", "searchWikipedia"),
    ("biography of Isaac Newton on wikipedia", "searchWikipedia"),
    ("what does wikipedia say about Mars", "searchWikipedia"),
    ("look up theory of relativity on wikipedia", "searchWikipedia"),
    ("wiki information on world war 2", "searchWikipedia"),
    ("search wikipedia for French Revolution", "searchWikipedia"),
    ("what is DNA according to wikipedia", "searchWikipedia"),
    ("wiki page of python programming language", "searchWikipedia"),
    ("read wikipedia article on Renaissance", "searchWikipedia"),
    ("search wiki for artificial intelligence", "searchWikipedia"),
    ("who was alexander the great according to wikipedia", "searchWikipedia"),

    # create_folder
    ("create a folder named test", "create_folder"),
    ("make a directory called project_files", "create_folder"),
    ("create folder assets", "create_folder"),
    ("make a new directory", "create_folder"),
    ("create a folder for photos", "create_folder"),
    ("create directory called src", "create_folder"),
    ("make a folder named documents", "create_folder"),
    ("create new directory backup", "create_folder"),
    ("make folder models", "create_folder"),
    ("i need a new folder called data", "create_folder"),
    ("create directory utils", "create_folder"),
    ("make a directory for assignments", "create_folder"),
    ("ek naya folder bana do", "create_folder"),
    ("create folder named temp", "create_folder"),
    ("make a directory test_dir", "create_folder"),
    ("create folder images", "create_folder"),
    ("make a new folder on my desktop", "create_folder"),
    ("create directory build", "create_folder"),

    # create_file
    ("create a file named notes.txt", "create_file"),
    ("make a file called todo.md", "create_file"),
    ("write a new file config.json", "create_file"),
    ("create a new file", "create_file"),
    ("new file please", "create_file"),
    ("make a text file", "create_file"),
    ("create script.py", "create_file"),
    ("create file named todo", "create_file"),
    ("make a file sample.csv", "create_file"),
    ("ek naya file bana do", "create_file"),
    ("touch main.py", "create_file"),
    ("create an empty file data.txt", "create_file"),
    ("make a new file called app.py", "create_file"),
    ("write a file named style.css", "create_file"),
    ("create file report.pdf", "create_file"),
    ("start a new document file", "create_file"),
    ("create a file called index.html", "create_file"),
    ("make file notes.md", "create_file"),

    # read_file
    ("read file notes.txt", "read_file"),
    ("what is inside readme.md", "read_file"),
    ("open and show me data.csv", "read_file"),
    ("display contents of script.py", "read_file"),
    ("read the config.json file", "read_file"),
    ("show me what is in todo.md", "read_file"),
    ("print the content of log.txt", "read_file"),
    ("view file index.html", "read_file"),
    ("cat main.py", "read_file"),
    ("open file results.txt and display it", "read_file"),
    ("show file contents for data.json", "read_file"),
    ("read contents of requirements.txt", "read_file"),
    ("check the content of file info.txt", "read_file"),
    ("display data from records.csv", "read_file"),
    ("open and read my notes.txt", "read_file"),
    ("view output.log", "read_file"),
    ("read what is written in summary.txt", "read_file"),
    ("show me the text in document.txt", "read_file"),

    # get_weather
    ("what's the weather in Delhi", "get_weather"),
    ("is it raining in Mumbai", "get_weather"),
    ("current temperature in New York", "get_weather"),
    ("what's the weather", "get_weather"),
    ("weather today", "get_weather"),
    ("is it raining outside", "get_weather"),
    ("tell me the temperature", "get_weather"),
    ("will it rain tomorrow", "get_weather"),
    ("weather forecast please", "get_weather"),
    ("aaj mausam kaisa hai", "get_weather"),
    ("how hot is it today", "get_weather"),
    ("check weather for delhi", "get_weather"),
    ("do i need an umbrella today", "get_weather"),
    ("kal mausam kaisa rahega", "get_weather"),
    ("weather update for london", "get_weather"),
    ("temperature in tokyo right now", "get_weather"),
    ("is it sunny in bangalore", "get_weather"),
    ("check humidity and precipitation today", "get_weather"),
    ("weather in seattle", "get_weather"),
    ("will it snow today", "get_weather"),

    # get_news
    ("give me today's top headlines", "get_news"),
    ("latest technology news", "get_news"),
    ("what's the news in sports", "get_news"),
    ("show me breaking news", "get_news"),
    ("latest world news today", "get_news"),
    ("news headlines for today", "get_news"),
    ("what is happening in politics news", "get_news"),
    ("give me financial news update", "get_news"),
    ("latest cricket news", "get_news"),
    ("show me entertainment news", "get_news"),
    ("top news stories right now", "get_news"),
    ("aaj ki taaja khabar", "get_news"),
    ("read today's daily news", "get_news"),
    ("give me the daily news digest", "get_news"),
    ("what are the global news headlines", "get_news"),
    ("business news updates today", "get_news"),
    ("what is in the morning news", "get_news"),
    ("fetch current news updates", "get_news"),

    # convert_currency
    ("convert 500 USD to INR", "convert_currency"),
    ("how much is 100 EUR in JPY", "convert_currency"),
    ("convert 50 GBP to CAD", "convert_currency"),
    ("convert 1000 rupees to dollars", "convert_currency"),
    ("how many euros is 50 USD", "convert_currency"),
    ("exchange rate from USD to INR", "convert_currency"),
    ("convert 250 AUD to EUR", "convert_currency"),
    ("what is 100 CAD in USD", "convert_currency"),
    ("convert 5000 yen to usd", "convert_currency"),
    ("currency conversion 200 euro in inr", "convert_currency"),
    ("convert 100 dollar to rupee", "convert_currency"),
    ("what is 50 pounds in dirhams", "convert_currency"),
    ("exchange 300 SGD to USD", "convert_currency"),
    ("convert 75 EUR to GBP", "convert_currency"),
    ("how much is 1000 INR in USD", "convert_currency"),
    ("currency exchange 500 USD to EUR", "convert_currency"),
    ("convert 200 AUD to INR", "convert_currency"),
    ("exchange rate between euro and dollar", "convert_currency"),

    # LLM
    ("hello", "LLM"),
    ("who are you", "LLM"),
    ("tell me a joke", "LLM"),
    ("explain binary search", "LLM"),
    ("write a poem", "LLM"),
    ("explain recursion", "LLM"),
    ("teach me binary trees", "LLM"),
    ("what is a linked list", "LLM"),
    ("how does gradient descent work", "LLM"),
    ("summarize this document for me", "LLM"),
    ("help me debug my code", "LLM"),
    ("explain how transformers work", "LLM"),
    ("what's the difference between tcp and udp", "LLM"),
    ("what is 2 plus 2", "LLM"),
    ("what is the meaning of life", "LLM"),
    ("write a short story about a robot", "LLM"),
    ("how do I cook pasta", "LLM"),
    ("tell me a motivational quote", "LLM"),
    ("hi how are you", "LLM"),
    ("explain quantum computing in simple words", "LLM"),
    ("what is the fullform of IEEE", "LLM"),
]
