TRAINING_DATA = [
    ("open youtube", "OPEN_WEBSITE"),
    ("launch google", "OPEN_WEBSITE"),
    ("open chatgpt", "OPEN_WEBSITE"),
    ("open spotify", "OPEN_WEBSITE"),
    ("go to instagram", "OPEN_WEBSITE"),
    ("open reddit for me", "OPEN_WEBSITE"),
    ("can you open netflix", "OPEN_WEBSITE"),
    ("open github", "OPEN_WEBSITE"),
    ("launch whatsapp web", "OPEN_WEBSITE"),
    ("open amazon", "OPEN_WEBSITE"),
    ("youtube khol do", "OPEN_WEBSITE"),
    ("google khol", "OPEN_WEBSITE"),
    ("open the youtube website", "OPEN_WEBSITE"),
    ("pls open instagram", "OPEN_WEBSITE"),
    ("open up youtube for me please", "OPEN_WEBSITE"),

    ("what's the weather", "WEATHER"),
    ("weather today", "WEATHER"),
    ("is it raining outside", "WEATHER"),
    ("tell me the temperature", "WEATHER"),
    ("will it rain tomorrow", "WEATHER"),
    ("weather forecast please", "WEATHER"),
    ("aaj mausam kaisa hai", "WEATHER"),
    ("how hot is it today", "WEATHER"),
    ("check weather for delhi", "WEATHER"),
    ("do i need an umbrella today", "WEATHER"),
    ("kal mausam kaisa rahega", "WEATHER"),
    ("weather update", "WEATHER"),

    ("create a new file", "CREATE_FILE"),
    ("make a file called notes", "CREATE_FILE"),
    ("new file please", "CREATE_FILE"),
    ("create notes.txt", "CREATE_FILE"),
    ("make a text file", "CREATE_FILE"),
    ("ek naya file bana do", "CREATE_FILE"),
    ("create a folder", "CREATE_FILE"),
    ("make a new directory", "CREATE_FILE"),
    ("create file named todo", "CREATE_FILE"),
    ("start a new document", "CREATE_FILE"),
    ("bana do ek naya document", "CREATE_FILE"),
    ("i need a new folder", "CREATE_FILE"),

    ("search for the nearest pizza place", "SEARCH_WEB"),
    ("search python tutorials", "SEARCH_WEB"),
    ("google the population of india", "SEARCH_WEB"),
    ("look up best laptops 2026", "SEARCH_WEB"),
    ("find me cricket scores", "SEARCH_WEB"),
    ("search karo iphone price", "SEARCH_WEB"),
    ("search for machine learning jobs", "SEARCH_WEB"),
    ("look up capital of france", "SEARCH_WEB"),
    ("find nearby restaurants", "SEARCH_WEB"),
    ("google search jiit placements", "SEARCH_WEB"),
    ("search for good running shoes", "SEARCH_WEB"),
    ("look up jiit hostel fees", "SEARCH_WEB"),
    ("find me some biryani places nearby", "SEARCH_WEB"),

    ("explain recursion", "LLM"),
    ("teach me binary trees", "LLM"),
    ("what is a linked list", "LLM"),
    ("how does gradient descent work", "LLM"),
    ("summarize this document for me", "LLM"),
    ("help me debug my code", "LLM"),
    ("explain how transformers work", "LLM"),
    ("what's the difference between tcp and udp", "LLM"),
    ("write a poem about the ocean", "LLM"),
    ("what is 2 plus 2", "LLM"),
    ("tell me a joke", "LLM"),
    ("what is the meaning of life", "LLM"),
    ("what is the fullform of IEEE", "LLM"),
]
